name: Docker Image CI

on:
  push:
    branches: 
      - main
      - feature/*
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get the Branch Name
      id: branch
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

    - name: Build the Docker Image
      run: docker build -t pos:${{steps.branch.outputs.branch}} .

    - name: Push the Docker image
      run: docker push pos:${{ steps.branch.outputs.branch }}
