name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Build the Docker image
      run: docker build . -f .codesandbox/Dockerfiel -t vsc-pos-system-forked--b579f87c547ac1ddade3246682489ca69cb9c586d72ddc024d7939a45947ead5-features:$(date +%s)

    - name: py-package-publish
      uses: mariamrf/py-package-publish-action@v1.1.0
      with:
        python_version: 3.7.0
        pip_version: latest
        subdir: # optional
