name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7  # Use the version you need

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Install Python dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install --upgrade pip
          pip install -r requirements.txt
        fi

    - name: Build Docker image
      run: docker build . -f .codesandbox/Dockerfile -t vsc-pos-system-forked--b579f87c547ac1ddade3246682489ca69cb9c586d72ddc024d7939a45947ead5-features:$(date +%s)

    - name: py-package-publish
      uses: mariamrf/py-package-publish-action@v1.1.0
      with:
        python_version: 3.7.0
        pip_version: latest
        subdir: # optional
